let app = angular.module('blog', ['ngRoute', 'ngSanitize', 'textAngular'])
.config(function($routeProvider,$locationProvider){
//$locationProvider.html5Mode(true);
$routeProvider.when('/index',{
    templateUrl:'partials/home.html',
});
$routeProvider.when('/single/:_id',{
    templateUrl:'partials/singlePost.html',
});
$routeProvider.when('/login/',{
    templateUrl:'partials/login.html',
});
$routeProvider.when('/admin/',{
    templateUrl:'partials/admin.html',
});
$routeProvider.when('/admin/new',{
    templateUrl:'partials/new.html',
});
$routeProvider.when('/admin/new-user',{
    templateUrl:'partials/new.html',
});
$routeProvider.otherwise({redirectTo:'/index'});
});
