let app = angular.module('blog', ['ngRoute', 'ngSanitize', 'textAngular'])
.config(function($routeProvider,$locationProvider){
//$locationProvider.html5Mode(true);
$routeProvider.when('/index',{
    templateUrl:'partials/home.html',
});
$routeProvider.when('/single/:_id',{
    templateUrl:'partials/singlePost.html',
});
$routeProvider.when('/login/',{
    templateUrl:'partials/login.html',
});
$routeProvider.when('/admin/',{
    templateUrl:'partials/admin.html',
});
$routeProvider.when('/admin/new-post',{
    templateUrl:'partials/new_post.html',
});
$routeProvider.when('/admin/posts',{
    templateUrl:'partials/post-list.html',
});
$routeProvider.when('/admin/new-user',{
    templateUrl:'partials/new_user.html',
});
$routeProvider.otherwise({redirectTo:'/index'});
});
